# Homework 6: Neural Networks
**Name:** Nicholas Starace  
**Student ID:** 4556822  
**D Value:** 22  

## Question 1: Conceptual Foundations

### Part A: Why Neural Networks?

**Written Response:** In homework 3, a logistic regression classifier was trained and implemented to predict if students were admitted or not admitted based on two of their exam scores. Using the sigmoid function, a linear decsion boundary was formed in part 1(g). This classifier had poor accuracy, correctly predicting admission with 60% accuracy in part 1(h). A nonlinear decision boundary may improve this accuracy, acheved with nonlinear models such as a neural network that creates new features as a nonlinear function of the input scores.  

### Part B: The Sigmoid's Role

**Written Response:**  
1. The dimension of Theta_1 is 3 rows by 5 columns. This theta has superscript 1 since it connects the weights from the first input layer to the second (hidden) layer. Number of rows are characterized by the number of nodes in the destination (hidden) layer. The number of columns are characterized by the number of nodes in the source (input) layer + 1 due to the bias feature.  
The dimension of Theta_2 is 2 rows by 4 columns. This theta has superscript 2 since it connects the weights from the second (hidden) layer to the third (output) layer. Number of rows are characterized by the number of nodes in the destination (output) layer. The number of columns are characterized by the number of nodes in the source (hidden) layer + 1 due to the bias feature.  
2. The sigmoid function introduces nonlinearity into the network, creating new hidden nodes as nonlinear functions of the input nodes determined by the sigmoid function selected. Without the sigmoid function, nodes in the hidden layer would be linear functions of the input nodes. Using this directly makes the classifier nearly identical to a logistic regression since the hidden layer nodes would be a weighted sum of the input layer nodes. 

### Part C: Forward vs. Backward

**Written Response:**  
1. During forward propogation, weights connecting each source to destination node are computed as a sigmoid function of the weighted sum. After the weighted sum is calculated, its sum is used as the input to the sigmoid function. The output of the sigmod function determines the values of the nodes in the destination layer.  
2. During back propagation, the neural network is trained by finding the error in the output layer and and using the chain rule to find the origin node of the error. These gradients are used to perform gradient descent and update weights and errors.  
3. Without forward propagation, the optimal theta matrices will never be computed. Due to the calulation of the sigmoid function in forward propagation, new errors are updated and minimized at the end of forward propagation. 

## Question 2: Building the Network Components

### Part A: Sigmoid and Sigmoid Gradient

In [82]:
# Import Libraries and Parameter Initialization
import numpy as np
D = 22

In [83]:
# Sigmoid Function
def sigmoid(z):
    g = 1 / (1 + np.exp(-z))                
    return g

In [84]:
# Sigmoid Gradient
def sigmoidGradient(z):
    g = sigmoid(z)
    dg = g * (1 - g)
    return dg

In [85]:
# Test and Verify Sigmoid Gradient
z = np.array([[-10], [0], [10]]) # [1 x 3]
zout = sigmoidGradient(z)
print(zout)

# Test and Verfy with D value
z = np.array([[-D/5], [0], [D/5]])
zout = sigmoidGradient(z)
print(zout)

[[4.53958077e-05]
 [2.50000000e-01]
 [4.53958077e-05]]
[[0.01198134]
 [0.25      ]
 [0.01198134]]


**Text Output:** Sigmoid gradient for z: [0.012; 0.25; 0.012]

### Part B: Forward Propagation

In [ ]:
def predict(Theta1, Theta2, X):
    numSamples = X.shape[0]
    numFeatures = X.shape[1]

    # Append Bias Column
    BiasX = np.ones((numSamples, 1))
    XBiased = np.hstack((BiasX, X))    # Use horrizontal stack to append bias column to input


    A2 = sigmoid(Theta1 @ XBiased)
    BiasA2 = np.ones((A2.shape[1], 1)) # Add Bias column to hidden layer

    h_x = sigmoid(Theta2 @ BiasA2)
    p = np.argmax(h_x, axis=1) # Take index of largest value across columns (1)

    return p, h_x

In [87]:
# Test Predict on Toy Data
Theta1_toy = np.array([[0.1 + (D/1000), 0.2, -0.3], [-0.1, 0.4 - (D/1000), 0.1]])
Theta2_toy = np.array([[0.3, -0.2 + (D/1000), 0.5], [-0.4, 0.1, -0.3 + (D/1000)]])
X_toy = np.array([[1, 0], [0, 1], [1, 1]])

p, h_x = predict(Theta1_toy, Theta2_toy, X_toy)
print(h_x)


[[0.65067328]
 [0.35939292]]


### Part C: Verification with Toy Data